version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
        volumes:
            - '.:/var/www/html'
        depends_on:
            - db
    db:
        image: 'postgres:latest'
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE}' # Configuração do banco de dados
            POSTGRES_USER: '${DB_USERNAME}' # Configuração do usuário
            POSTGRES_PASSWORD: '${DB_PASSWORD}' # Configuração da senha
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data:
