version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '80:80'
        volumes:
            - '.:/var/www/html'
        depends_on:
            - db
    db:
        image: 'postgres:latest'
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - db_data:/var/lib/postgresql/data
volumes:
    db_data:
